"""
CSV 전체 데이터 → Supabase accounts 재시딩
기기명(device) 제외, 나머지 28개 필드 전부 metadata에 저장
1인 = 1 account row (모든 UID를 metadata 안에)
"""
import json
import urllib.request

SUPABASE_URL = "https://okucjwgihcirnilnfdic.supabase.co"
SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rdWNqd2dpaGNpcm5pbG5mZGljIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzA2MDY4MiwiZXhwIjoyMDg4NjM2NjgyfQ.IUlQ3UHHUZ2om8VcynBnHu8crajNDMP7mSIcXFME8Tw"

HEADERS = {
    "apikey": SERVICE_KEY,
    "Authorization": f"Bearer {SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation",
}


def api_request(method, table, data=None, params=""):
    url = f"{SUPABASE_URL}/rest/v1/{table}"
    if params:
        url += f"?{params}"
    body = json.dumps(data).encode("utf-8") if data else None
    req = urllib.request.Request(url, body, HEADERS, method=method)
    try:
        resp = urllib.request.urlopen(req)
        return json.loads(resp.read())
    except Exception as e:
        print(f"  ERROR {method} {table}: {e}")
        if hasattr(e, "read"):
            print(f"  Detail: {e.read().decode()[:300]}")
        return None


def api_get(table, params=""):
    return api_request("GET", table, params=params)


def api_post(table, data):
    return api_request("POST", table, data)


def api_delete(table, params=""):
    return api_request("DELETE", table, params=params)


# ============================================================
# 1. 트레이더 맵 가져오기
# ============================================================
existing_traders = api_get("traders", "select=id,name")
trader_map = {t["name"]: t["id"] for t in existing_traders}
print(f"트레이더 {len(trader_map)}명: {list(trader_map.keys())}")

# ============================================================
# 2. 기존 accounts 전부 삭제
# ============================================================
print("\n기존 accounts 삭제 중...")
# neq. 조건으로 전체 삭제 (PostgREST는 조건 없는 DELETE 불가)
result = api_delete("accounts", "id=neq.00000000-0000-0000-0000-000000000000")
if result is not None:
    print(f"  삭제 완료: {len(result)}개")
else:
    print("  삭제 실패 또는 이미 비어있음")

# ============================================================
# 3. CSV 전체 데이터 (기기명 제외)
# ============================================================
# 각 딕셔너리의 키는 kyc-account-form.tsx의 SECTIONS 필드 key와 일치
accounts_data = [
    {
        # affiliate 계정 - 오수정
        "brought_by": "오수정",
        "code": "affiliate",
        "kyc_name": "오수정",
        "eng_name": "OH SUJEONG",
        "birth": "950131",
        "gmail": "leeflow862@gmail.com",
        "gmail_pw": "aegis8832!",
        "exchange_pw": "Flow70930!!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "",
        "uid_ourbit": "-",
        "uid_picol": "-",
        "uid_tapbit": "-",
        "uid_digifinex": "-",
        "uid_jucom": "-",
        "uid_bitget": "-",
        "uid_biconomy": "",
        "sim_owner": "이용덕1",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-2177-3880",
        "carrier": "아이즈모바일 SKT",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "-",
        "prepaid_account": "-",
        "_manager": "오수정",
    },
    {
        # 1-1 윤성현
        "code": "1-1",
        "kyc_name": "윤성현",
        "brought_by": "윤성현",
        "eng_name": "Yun seonghyun",
        "birth": "830911",
        "gmail": "stonewave67@gmail.com",
        "gmail_pw": "Leesang00!!",
        "exchange_pw": "Leesang00!!",
        "pin": "679336",
        "google_otp": "0",
        "recovery_email": "",
        "uid_ourbit": "65525710",
        "uid_picol": "76349617",
        "uid_tapbit": "96908544",
        "uid_digifinex": "재가입중",
        "uid_jucom": "290402859719",
        "uid_bitget": "9304415186",
        "uid_biconomy": "",
        "sim_owner": "윤성현1",
        "sim_brought_by": "윤성현",
        "sim_org": "AGS",
        "phone": "010-5567-9336",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "윤성현",
    },
    {
        # 1-2 강정현
        "code": "1-2",
        "kyc_name": "강정현",
        "brought_by": "강정현",
        "eng_name": "Kang jenghyun",
        "birth": "870113",
        "gmail": "fastcloud808@gmail.com",
        "gmail_pw": "Angry7788!!",
        "exchange_pw": "Angry7788!!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "",
        "uid_ourbit": "00196200",
        "uid_picol": "80673687",
        "uid_tapbit": "탈퇴 후 재가입 필요",
        "uid_digifinex": "1725823495",
        "uid_jucom": "290404742031",
        "uid_bitget": "1882387960",
        "uid_biconomy": "",
        "sim_owner": "오수정2",
        "sim_brought_by": "오수정",
        "sim_org": "AGS",
        "phone": "010-2394-9809",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "uuuuu01230",
        "carrier_pw": "1122cats",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 1-3 김솔아
        "code": "1-3",
        "kyc_name": "김솔아",
        "brought_by": "강정현",
        "eng_name": "Kim solah",
        "birth": "911018",
        "gmail": "darkmint851@gmail.com",
        "gmail_pw": "Makers8098!!",
        "exchange_pw": "Makers8098!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "jaycrypto0213@gmail.com",
        "uid_ourbit": "25909770",
        "uid_picol": "20992411",
        "uid_tapbit": "96908559",
        "uid_digifinex": "1725964500",
        "uid_jucom": "290404784850",
        "uid_bitget": "3545388047",
        "uid_biconomy": "",
        "sim_owner": "윤성현2",
        "sim_brought_by": "윤성현",
        "sim_org": "AGS",
        "phone": "010-7743-3992",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 1-4 최대길
        "code": "1-4",
        "kyc_name": "최대길",
        "brought_by": "강정현",
        "eng_name": "choi daegil",
        "birth": "891102",
        "gmail": "jaycrypto0213@gmail.com",
        "gmail_pw": "Cryptojay2002!!",
        "exchange_pw": "Cryptojay2002!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "",
        "uid_ourbit": "13664102(레퍼럴 이전 신청중)",
        "uid_picol": "94155745",
        "uid_tapbit": "96908557",
        "uid_digifinex": "1725677499",
        "uid_jucom": "290403418549",
        "uid_bitget": "2994569677",
        "uid_biconomy": "",
        "sim_owner": "김수환2",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-8157-0811",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 1-5 김수환
        "code": "1-5",
        "kyc_name": "김수환",
        "brought_by": "이용덕",
        "eng_name": "suhwan kim",
        "birth": "890108",
        "gmail": "kswanswan89@gmail.com",
        "gmail_pw": "Kswan8098!",
        "exchange_pw": "Kswan8098!",
        "pin": "260128",
        "google_otp": "0",
        "recovery_email": "boxgreen010@gmail.com",
        "uid_ourbit": "72808549",
        "uid_picol": "22178183",
        "uid_tapbit": "96908459",
        "uid_digifinex": "1725594619",
        "uid_jucom": "290403527505",
        "uid_bitget": "4007897160",
        "uid_biconomy": "",
        "sim_owner": "김수환1",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-8132-0810",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "이용덕",
    },
    {
        # 1-6 심준보
        "code": "1-6",
        "kyc_name": "심준보",
        "brought_by": "이용덕",
        "eng_name": "shim junbo",
        "birth": "900103",
        "gmail": "boxgreen010@gmail.com",
        "gmail_pw": "Dote707070!!",
        "exchange_pw": "Dote707070!!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "kinbo474@gmail.com",
        "uid_ourbit": "85383730",
        "uid_picol": "65806809",
        "uid_tapbit": "96908571",
        "uid_digifinex": "1725202492",
        "uid_jucom": "290404342243",
        "uid_bitget": "2788498646",
        "uid_biconomy": "",
        "sim_owner": "오수정1",
        "sim_brought_by": "오수정",
        "sim_org": "AGS",
        "phone": "010-8173-9809",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "uuuuu01230",
        "carrier_pw": "1122cats",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "이용덕",
    },
    {
        # 1-7 최지민
        "code": "1-7",
        "kyc_name": "최지민",
        "brought_by": "이용덕",
        "eng_name": "CHOI JIMIN",
        "birth": "900328",
        "gmail": "kinbo474@gmail.com",
        "gmail_pw": "aegis8832!",
        "exchange_pw": "KINbo112112!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "openpath752@gmail.com",
        "uid_ourbit": "93870260(레퍼럴 이전 신청중)",
        "uid_picol": "6678 1203",
        "uid_tapbit": "96907734",
        "uid_digifinex": "1726810086",
        "uid_jucom": "290405706583",
        "uid_bitget": "4806060242",
        "uid_biconomy": "",
        "sim_owner": "강정현1",
        "sim_brought_by": "강정현",
        "sim_org": "협업팀",
        "phone": "010-5934-3631",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "선불",
        "postpaid_end": "-",
        "prepaid_account": "국민은행 219-6907-4368-197 / 36,000원",
        "_manager": "이용덕",
    },
    {
        # 1-8 이정빈
        "code": "1-8",
        "kyc_name": "이정빈",
        "brought_by": "이용덕",
        "eng_name": "lee jungbin",
        "birth": "900821",
        "gmail": "openpath752@gmail.com",
        "gmail_pw": "Dragon8098!",
        "exchange_pw": "Dragon8098!",
        "pin": "",
        "google_otp": "0",
        "recovery_email": "yongdeok866@gmail.com",
        "uid_ourbit": "48356682",
        "uid_picol": "74398327",
        "uid_tapbit": "96908567",
        "uid_digifinex": "1725507497",
        "uid_jucom": "290420443977",
        "uid_bitget": "3548193279",
        "uid_biconomy": "",
        "sim_owner": "이용덕2",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-5641-4711",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "이용덕",
    },
    {
        # 2-1
        "code": "2-1",
        "kyc_name": "2-1",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "nahyeonu504@gmail.com",
        "gmail_pw": "zxzx1122!!",
        "exchange_pw": "Zxzx1122!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "45631701",
        "uid_picol": "38868717",
        "uid_tapbit": "96898302",
        "uid_digifinex": "1730441864",
        "uid_jucom": "291106928728",
        "uid_bitget": "3797906678",
        "uid_biconomy": "",
        "sim_owner": "김종숙1",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-5568-8156",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-09-23",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-2
        "code": "2-2",
        "kyc_name": "2-2",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "ghostdevil1923@gmail.com",
        "gmail_pw": "qwqw1212!!",
        "exchange_pw": "Qwqw1212!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "12396134",
        "uid_picol": "88484407",
        "uid_tapbit": "96898287",
        "uid_digifinex": "1730521883",
        "uid_jucom": "291118080670",
        "uid_bitget": "6143840020",
        "uid_biconomy": "",
        "sim_owner": "이규갑2",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-5703-2293",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-09-23",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-3
        "code": "2-3",
        "kyc_name": "2-3",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "useong7788@gmail.com",
        "gmail_pw": "Aass1122!!",
        "exchange_pw": "Aass1122!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "kwhales1923@gmail.com",
        "uid_ourbit": "21022043",
        "uid_picol": "17595567",
        "uid_tapbit": "96900548",
        "uid_digifinex": "1732597651",
        "uid_jucom": "292515228308",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "황미숙1",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-8340-3620",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-10-03",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-4 장현구
        "code": "2-4",
        "kyc_name": "장현구",
        "brought_by": "강정현",
        "eng_name": "jang hyun gu",
        "birth": "890306",
        "gmail": "kwhales1923@gmail.com",
        "gmail_pw": "Ccvv3344!!",
        "exchange_pw": "Ccvv3344!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "61648083",
        "uid_picol": "23645601",
        "uid_tapbit": "96900596",
        "uid_digifinex": "1732077661",
        "uid_jucom": "292524859774",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "황미숙2",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-8140-3762",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-10-03",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-5 이제현
        "code": "2-5",
        "kyc_name": "이제현",
        "brought_by": "강정현",
        "eng_name": "LEE JEHYEON",
        "birth": "890724",
        "gmail": "stonebird235@gmail.com",
        "gmail_pw": "Cats1122!!",
        "exchange_pw": "Cats1122!!",
        "pin": "",
        "google_otp": "X",
        "recovery_email": "",
        "uid_ourbit": "98851632",
        "uid_picol": "18185079",
        "uid_tapbit": "96908562",
        "uid_digifinex": "1725481498",
        "uid_jucom": "290403994489",
        "uid_bitget": "3981923000",
        "uid_biconomy": "",
        "sim_owner": "김경환2",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-5570-9167",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-6 심기용
        "code": "2-6",
        "kyc_name": "심기용",
        "brought_by": "강정현",
        "eng_name": "",
        "birth": "900225",
        "gmail": "godopp1923@gmail.com",
        "gmail_pw": "Wewe2323!!",
        "exchange_pw": "Wewe2323!!",
        "pin": "",
        "google_otp": "X",
        "recovery_email": "",
        "uid_ourbit": "82659104",
        "uid_picol": "84998137",
        "uid_tapbit": "96898286",
        "uid_digifinex": "1730651880",
        "uid_jucom": "291116395289",
        "uid_bitget": "9457351915",
        "uid_biconomy": "",
        "sim_owner": "이규갑1",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-5535-2293",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-09-23",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-7 유길호
        "code": "2-7",
        "kyc_name": "유길호",
        "brought_by": "강정현",
        "eng_name": "Yu gilho",
        "birth": "890910",
        "gmail": "gitaebae480@gmail.com",
        "gmail_pw": "xcxc2233!!",
        "exchange_pw": "Xcxc2233!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "65480076",
        "uid_picol": "13100769",
        "uid_tapbit": "96898285",
        "uid_digifinex": "1730834875",
        "uid_jucom": "291114912681",
        "uid_bitget": "4203341112",
        "uid_biconomy": "",
        "sim_owner": "김종숙2",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-5736-8156",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-09-23",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-8 예정
        "code": "2-8",
        "kyc_name": "예정",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "daewong750@gmail.com",
        "gmail_pw": "Ddff3344!!",
        "exchange_pw": "Ddff3344!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "",
        "uid_picol": "",
        "uid_tapbit": "",
        "uid_digifinex": "",
        "uid_jucom": "",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "박유환1",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-8228-6656",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-10-04",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-9 예정
        "code": "2-9",
        "kyc_name": "예정",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "taehyeong99888@gmail.com",
        "gmail_pw": "Ssdd2233!!",
        "exchange_pw": "Ssdd2233!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "",
        "uid_picol": "",
        "uid_tapbit": "",
        "uid_digifinex": "",
        "uid_jucom": "",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "박유환2",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-5369-4301",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-10-04",
        "prepaid_account": "-",
        "_manager": "강정현",
    },
    {
        # 2-10 USIM 공기계
        "code": "2-10",
        "kyc_name": "USIM 공기계",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "kimkyunga9@gmail.com",
        "gmail_pw": "",
        "exchange_pw": "Nnmm9900!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "",
        "uid_picol": "",
        "uid_tapbit": "",
        "uid_digifinex": "",
        "uid_jucom": "",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "이용덕1",
        "sim_brought_by": "이용덕",
        "sim_org": "AGS",
        "phone": "010-3970-4711",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "leeflow862",
        "carrier_pw": "70930flow",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "이용덕",
    },
    {
        # 2-11 김경환
        "code": "2-11",
        "kyc_name": "김경환",
        "brought_by": "김경환",
        "eng_name": "Kim kyunghwan",
        "birth": "920517",
        "gmail": "yongdeok866@gmail.com",
        "gmail_pw": "",
        "exchange_pw": "Hipo0909!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "51824584(KYC 필요)",
        "uid_picol": "17760691",
        "uid_tapbit": "96908553",
        "uid_digifinex": "1725160502",
        "uid_jucom": "290404426665",
        "uid_bitget": "1978472122",
        "uid_biconomy": "",
        "sim_owner": "김경환1",
        "sim_brought_by": "김경환",
        "sim_org": "AGS",
        "phone": "010-8211-9167",
        "carrier": "이야기모바일 LGU+",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "후불",
        "postpaid_end": "2026-08-26",
        "prepaid_account": "-",
        "_manager": "김경환",
    },
    {
        # 3-1
        "code": "3-1",
        "kyc_name": "3-1",
        "brought_by": "",
        "eng_name": "",
        "birth": "",
        "gmail": "kimdohwa19@gmail.com",
        "gmail_pw": "",
        "exchange_pw": "Bbnn8899!!",
        "pin": "",
        "google_otp": "",
        "recovery_email": "",
        "uid_ourbit": "",
        "uid_picol": "",
        "uid_tapbit": "",
        "uid_digifinex": "",
        "uid_jucom": "",
        "uid_bitget": "",
        "uid_biconomy": "",
        "sim_owner": "",
        "sim_brought_by": "",
        "sim_org": "",
        "phone": "",
        "carrier": "",
        "carrier_id": "",
        "carrier_pw": "",
        "payment_type": "",
        "postpaid_end": "",
        "prepaid_account": "",
        "_manager": "강정현",
    },
]

# ============================================================
# 4. 계정 삽입
# ============================================================
print(f"\n{len(accounts_data)}개 계정 삽입 중...")
success_count = 0

for acct in accounts_data:
    manager_name = acct.pop("_manager")
    manager_id = trader_map.get(manager_name)
    if not manager_id:
        print(f"  SKIP {acct.get('kyc_name')}: 관리자 '{manager_name}' 없음")
        continue

    kyc_name = acct.get("kyc_name", "")
    code = acct.get("code", "")
    alias = f"{kyc_name}_{code}" if kyc_name else f"account_{code}"

    # UID가 있는 첫 번째 거래소를 exchange 컬럼에 설정
    exchange_map = {
        "uid_bitget": "Bitget",
        "uid_picol": "Picol",
        "uid_tapbit": "Tapbit",
        "uid_digifinex": "Digifinex",
        "uid_jucom": "Jucom",
        "uid_biconomy": "Biconomy",
        "uid_ourbit": "Ourbit",
    }
    exchange = "Bitget"  # 기본값
    for uid_key, ex_name in exchange_map.items():
        val = acct.get(uid_key, "")
        if val and val != "-":
            exchange = ex_name
            break

    result = api_post("accounts", {
        "trader_id": manager_id,
        "alias": alias,
        "exchange": exchange,
        "status": "active",
        "metadata": acct,
    })

    if result:
        success_count += 1
        print(f"  OK: {alias} ({exchange})")
    else:
        print(f"  FAIL: {alias}")

print(f"\n=== 완료 ===")
print(f"총 {success_count}/{len(accounts_data)}개 계정 등록")
